name: 'Update Angular Action'
on: 
    workflow_dispatch: # Allows manual triggering
  
jobs:
 ngxUptodate:
   runs-on: ubuntu-latest
   steps:
     - name: Updating ng dependencies # the magic happens here !
       uses: fast-facts/ng-update@v1
       with:
         base-branch: master
         repo-token: ${{ secrets.GITHUB_TOKEN }}
